#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    outputs:
      image-tag: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      - name: Configure Docker for Google  Artifact Registry
        run: |
          gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev
      - name: Build and push (dev
        run: |
          IMAGE_TAG=${GCP_REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/message-repo/message-api:${GITHUB_SHA}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG)
